USE [master]
GO
/****** Object:  Database [MMMGame]    Script Date: 09/01/2019 12:01:50 ******/
CREATE DATABASE [MMMGame]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MMMGame', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\MMMGame.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MMMGame_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\MMMGame_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [MMMGame] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MMMGame].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MMMGame] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MMMGame] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MMMGame] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MMMGame] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MMMGame] SET ARITHABORT OFF 
GO
ALTER DATABASE [MMMGame] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MMMGame] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MMMGame] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MMMGame] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MMMGame] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MMMGame] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MMMGame] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MMMGame] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MMMGame] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MMMGame] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MMMGame] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MMMGame] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MMMGame] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MMMGame] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MMMGame] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MMMGame] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MMMGame] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MMMGame] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [MMMGame] SET  MULTI_USER 
GO
ALTER DATABASE [MMMGame] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MMMGame] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MMMGame] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MMMGame] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MMMGame] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MMMGame] SET QUERY_STORE = OFF
GO
USE [MMMGame]
GO
/****** Object:  Table [dbo].[ContactMessages]    Script Date: 09/01/2019 12:01:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ContactMessages](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Date] [date] NOT NULL,
	[PhoneNumber] [nvarchar](50) NULL,
	[Email] [nvarchar](100) NULL,
	[Message] [nvarchar](250) NOT NULL,
 CONSTRAINT [PK_ContactMessages] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Feedbacks]    Script Date: 09/01/2019 12:01:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Feedbacks](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
	[Date] [datetime] NOT NULL,
	[Subject] [nvarchar](250) NOT NULL,
	[Content] [nvarchar](250) NOT NULL,
 CONSTRAINT [PK_feedbacks] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Images]    Script Date: 09/01/2019 12:01:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Images](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Images] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Results]    Script Date: 09/01/2019 12:01:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Results](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NOT NULL,
	[Date] [datetime] NOT NULL,
	[Duration] [int] NOT NULL,
	[MovesCount] [int] NOT NULL,
	[Score] [int] NOT NULL,
	[Difficulty] [int] NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
	[FullName] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_GameRounds] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 09/01/2019 12:01:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](100) NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[BirthDate] [date] NULL,
	[RegisterDate] [date] NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [MMMGame] SET  READ_WRITE 
GO
